apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-dcohrwkv
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-dcohrwkv:65312976382ed79b1d009f0314755d0fdeff047d@sha256:c77da84f7368858c4ba628f450442c7bedcc642391a8dd9a31ed0c71080990e7
        name: container-image  
